id: P006793
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:23:13.011032
source_metadata:
  id: bdr:W19479
  title: ཀུན་དགའ་རྒྱལ་མཚན་གྱི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    63947f8407f04f46bafc770a7425018c:
      image_group_id: I1GS105458
      title: ''
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
