id: P006793
initial_creation_type: ocr
source_metadata:
  id: bdr:W19479
  title: ཀུན་དགའ་རྒྱལ་མཚན་གྱི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    63947f8407f04f46bafc770a7425018c:
      image_group_id: I1GS105458
      title: ''
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
